package Bulletin.UI;


public class BarreMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public BarreMenu() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MPersonne = new javax.swing.JMenu();
        MIdentification = new javax.swing.JMenuItem();
        ListePersonne = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        MAdmin = new javax.swing.JMenu();
        AdmIden = new javax.swing.JMenuItem();
        MdpChange = new javax.swing.JMenuItem();
        Info_Connex = new javax.swing.JMenuItem();
        MAide = new javax.swing.JMenu();
        MAbout = new javax.swing.JMenuItem();
        MContact = new javax.swing.JMenuItem();

        jMenu6.setText("jMenu6");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu12.setText("jMenu12");

        jMenuItem16.setText("jMenuItem16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setResizable(false);

        MPersonne.setText("Personne");

        MIdentification.setText("Identification");
        MIdentification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIdentificationActionPerformed(evt);
            }
        });
        MPersonne.add(MIdentification);

        ListePersonne.setText("Liste");
        ListePersonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListePersonneActionPerformed(evt);
            }
        });
        MPersonne.add(ListePersonne);

        jMenuBar1.add(MPersonne);

        jMenu7.setText("Options");

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem13.setText("Profile Entry");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem13);

        jMenuBar1.add(jMenu7);

        MAdmin.setText("Admin");

        AdmIden.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK));
        AdmIden.setText("Identification");
        AdmIden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmIdenActionPerformed(evt);
            }
        });
        MAdmin.add(AdmIden);

        MdpChange.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MdpChange.setText("Changer de mot de passe");
        MdpChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MdpChangeActionPerformed(evt);
            }
        });
        MAdmin.add(MdpChange);

        Info_Connex.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        Info_Connex.setText("Détails de connexion");
        Info_Connex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Info_ConnexActionPerformed(evt);
            }
        });
        MAdmin.add(Info_Connex);

        jMenuBar1.add(MAdmin);

        MAide.setText("Aide");
        MAide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAideActionPerformed(evt);
            }
        });

        MAbout.setText("A propos");
        MAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAboutActionPerformed(evt);
            }
        });
        MAide.add(MAbout);

        MContact.setText("Contact");
        MContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MContactActionPerformed(evt);
            }
        });
        MAide.add(MContact);

        jMenuBar1.add(MAide);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdmIdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmIdenActionPerformed
    AdIdentification frm = new AdIdentification();
    frm.setVisible(true); 
    }//GEN-LAST:event_AdmIdenActionPerformed

    private void MdpChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MdpChangeActionPerformed
    ChangePassword frm = new ChangePassword();
    frm.setVisible(true); 
    }//GEN-LAST:event_MdpChangeActionPerformed

    private void Info_ConnexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info_ConnexActionPerformed
    InfoConnexion frm = new InfoConnexion();
    frm.setVisible(true); 
    }//GEN-LAST:event_Info_ConnexActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
     Administrateur frm= new Administrateur();
     frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void MAideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAideActionPerformed
   
    }//GEN-LAST:event_MAideActionPerformed

    // Pour ouvrir About
    private void MAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAboutActionPerformed
     About frm= new About();
     frm.setVisible(true);
    }//GEN-LAST:event_MAboutActionPerformed

    private void MIdentificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIdentificationActionPerformed
    AjoutPersonne frm= new AjoutPersonne();
    frm.setVisible(true);
    }//GEN-LAST:event_MIdentificationActionPerformed

    private void ListePersonneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListePersonneActionPerformed
    //Services frm= new Services();
    //frm.setVisible(true);
    }//GEN-LAST:event_ListePersonneActionPerformed

    
    // Pour ouvrir la page Contact
    private void MContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MContactActionPerformed
     Contact frm = new Contact();
     frm.setVisible(true);
    }//GEN-LAST:event_MContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarreMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarreMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarreMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarreMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarreMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AdmIden;
    private javax.swing.JMenuItem Info_Connex;
    private javax.swing.JMenuItem ListePersonne;
    private javax.swing.JMenuItem MAbout;
    private javax.swing.JMenu MAdmin;
    private javax.swing.JMenu MAide;
    private javax.swing.JMenuItem MContact;
    private javax.swing.JMenuItem MIdentification;
    private javax.swing.JMenu MPersonne;
    private javax.swing.JMenuItem MdpChange;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
